# Generated by Django 5.2.12 on 2026-04-06 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_song_album_song_artwork_url_song_genre_song_plays_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='external_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='song',
            name='source',
            field=models.CharField(default='local', max_length=50),
        ),
    ]
