# Generated by Django 5.2.12 on 2026-04-25 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_song_external_id_song_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='songs',
            field=models.ManyToManyField(related_name='playlists', through='core.PlaylistSong', to='core.song'),
        ),
    ]
